vsphere_user      = "vSphere Username"
vsphere_password  = "vSphare Username Password"
vsphere_server    = "vSphere Ip adderess"
admin_password    = "Windows Admin Password"
datacenter        = "vShpere Datacenter Name"
cluster           = "VShpere Cluster Name"
template          = "Windows Server Template Name"
