
- name: Copy extadsch C drive
  tags: domains
  ansible.windows.win_copy:
    src: "/home/xtream/gptfinal/ansible/roles/mecm/files/ConfigMgr2403/Source/SMSSETUP/BIN/X64/extadsch.exe"
    dest: "C:\\"

- name: Check if extadsch.exe exists
  tags: domains
  ansible.windows.win_stat:
    path: 'C:\extadsch.exe'
  register: extadsch_file

- name: Fail if extadsch.exe not found
  tags: domains
  fail:
    msg: "Extend ConfigMgr Schema: extadsch.exe was not found at C:\\extadsch.exe"
  when: not extadsch_file.stat.exists

- name: Run extadsch.exe to extend schema
  tags: domains
  ansible.windows.win_command: 'C:\extadsch.exe'
  register: extend_schema_result

# Give the system a moment to write the log file if needed
- name: Wait briefly to ensure log file is written
  tags: domains
  pause:
    seconds: 5

- name: Check ExtADSch.log for success message
  tags: domains
  ansible.windows.win_shell: 'Select-String -Path "C:\ExtADSch.log" -Pattern "Successfully extended the Active Directory schema"'
  register: schema_log_check
  failed_when: schema_log_check.rc != 0
  changed_when: false

- name: Confirm schema extension success
  tags: domains
  debug:
    msg: "Schema extended successfully"